"""add_dedup_columns

Revision ID: 86764e1497f6
Revises: 
Create Date: 2026-03-18 20:22:13.217579

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '86764e1497f6'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('likes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('post_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['post_id'], ['posts.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.add_column('posts', sa.Column('content_hash', sa.String(length=64), nullable=True))
    op.add_column('posts', sa.Column('content_vector', sa.Text(), nullable=True))
    op.create_index(op.f('ix_posts_content_hash'), 'posts', ['content_hash'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_posts_content_hash'), table_name='posts')
    op.drop_column('posts', 'content_vector')
    op.drop_column('posts', 'content_hash')
    op.drop_table('likes')
    # ### end Alembic commands ###
